"""add_code_entity_and_file_lexical_columns

Revision ID: 4e35f936f155
Revises: ac345e6d86ce
Create Date: 2026-07-24 00:29:23.720335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e35f936f155'
down_revision: Union[str, Sequence[str], None] = 'ac345e6d86ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pg_trgm powers trigram-based fuzzy/substring matching on code_entity.name
    # (e.g. "createTok" finding "createToken") — not built into Postgres by
    # default, so it must be enabled once per database before its operator
    # class (gin_trgm_ops, used below) can be referenced by an index.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('FUNCTION', 'CLASS', 'METHOD', name='entity_kind'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_entities_file_id'), 'code_entities', ['file_id'], unique=False)
    op.create_index(op.f('ix_code_entities_repository_id'), 'code_entities', ['repository_id'], unique=False)
    op.create_index('ix_code_entities_repository_id_name', 'code_entities', ['repository_id', 'name'], unique=False)

    # Unlike `code_entities.kind` above — which got its enum type auto-created
    # for free because CREATE TABLE handles that — adding an enum column to an
    # *existing* table via ALTER TABLE does not auto-create the type. It has to
    # be created explicitly first; `create_type=False` on the column below then
    # tells SQLAlchemy not to try (and fail) to create it a second time.
    file_language_enum = postgresql.ENUM("PYTHON", "JAVASCRIPT", "TYPESCRIPT", name="file_language")
    file_language_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "files",
        sa.Column("language", sa.Enum("PYTHON", "JAVASCRIPT", "TYPESCRIPT", name="file_language", create_type=False), nullable=True),
    )
    op.add_column('files', sa.Column('loc', sa.Integer(), nullable=True))
    op.add_column('files', sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(content, ''))", persisted=True), nullable=True))
    op.create_index('ix_files_repository_id_content_hash', 'files', ['repository_id', 'content_hash'], unique=False)
    # ### end Alembic commands ###

    # GIN on content_tsv is the actual lexical-search index (docs/DATA_MODEL.md) —
    # autogenerate doesn't emit this on its own since a plain `Index(...)` in the
    # model defaults to a btree, and a btree can't index a tsvector's match
    # operator (`@@`) at all. Same reasoning for the trigram index below.
    op.execute("CREATE INDEX ix_files_content_tsv ON files USING gin (content_tsv)")
    op.execute("CREATE INDEX ix_code_entities_name_trgm ON code_entities USING gin (name gin_trgm_ops)")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_code_entities_name_trgm")
    op.execute("DROP INDEX IF EXISTS ix_files_content_tsv")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_repository_id_content_hash', table_name='files')
    op.drop_column('files', 'content_tsv')
    op.drop_column('files', 'loc')
    op.drop_column('files', 'language')
    postgresql.ENUM(name="file_language").drop(op.get_bind(), checkfirst=True)
    op.drop_index('ix_code_entities_repository_id_name', table_name='code_entities')
    op.drop_index(op.f('ix_code_entities_repository_id'), table_name='code_entities')
    op.drop_index(op.f('ix_code_entities_file_id'), table_name='code_entities')
    op.drop_table('code_entities')
    # ### end Alembic commands ###
