"""add_chunk_model

Revision ID: 7c1a4b9e2d33
Revises: fb86cf1b15fb
Create Date: 2026-07-25 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c1a4b9e2d33'
down_revision: Union[str, Sequence[str], None] = 'fb86cf1b15fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Hand-written rather than autogenerated: autogenerate can't see the raw-SQL GIN
    # indexes from 4e35f936f155 in its model diff and proposes dropping them on any
    # later table change (noted in docs/SESSION_LOG.md).
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embed_text', sa.Text(), nullable=False),
    sa.Column('content_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', coalesce(embed_text, ''))", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['code_entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_repository_id'), 'chunks', ['repository_id'], unique=False)
    op.create_index(op.f('ix_chunks_file_id'), 'chunks', ['file_id'], unique=False)

    # The actual chunk-level lexical index. A plain Index(...) in the model would default
    # to a btree, which cannot index a tsvector's match operator (`@@`) at all — same
    # reasoning as ix_files_content_tsv in 4e35f936f155.
    op.execute("CREATE INDEX ix_chunks_content_tsv ON chunks USING gin (content_tsv)")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_chunks_content_tsv")
    op.drop_index(op.f('ix_chunks_file_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_repository_id'), table_name='chunks')
    op.drop_table('chunks')
