"""add_chunk_embedding_column

Revision ID: b3f4c9a1d2e6
Revises: 7a96b345a5d0
Create Date: 2026-07-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b3f4c9a1d2e6'
down_revision: Union[str, Sequence[str], None] = '7a96b345a5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector gives Postgres the `vector` column type and the `<=>` cosine-distance
    # operator — without this extension there is nowhere to put an embedding at all.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Hand-written, not autogenerated: autogenerate can't see the raw-SQL GIN indexes
    # from earlier migrations in its model diff and proposes dropping them (same trap
    # noted in 7c1a4b9e2d33). Nullable is load-bearing, not defensive — the M6 embedding
    # stage selects WHERE embedding IS NULL so a 429 partway through a repo resumes
    # instead of restarting, and a repo stuck mid-embed stays searchable via lexical.
    #
    # No HNSW/IVFFlat index here (see docs/DATA_MODEL.md's deferred-and-why entry): our
    # per-file cap forces a full sort over every chunk in the repo already, so an ANN
    # index would sit unused by the only query that reads this column. Exact cosine
    # search over a few thousand chunks is tens of milliseconds — fast enough as-is.
    op.add_column('chunks', sa.Column('embedding', Vector(1536), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('chunks', 'embedding')
