"""add_chunk_embedding_column

Revision ID: b3f4c9a1d2e6
Revises: 7a96b345a5d0
Create Date: 2026-07-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'b3f4c9a1d2e6'
down_revision: Union[str, Sequence[str], None] = '7a96b345a5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector gives Postgres the `vector` column type and the `<=>` cosine-distance
    # operator — without this extension there is nowhere to put an embedding at all.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # Hand-written rather than autogenerated. The reason recorded here was WRONG and is
    # corrected in place: autogenerate has no trouble seeing a GIN index — it proposed
    # dropping ix_files_content_tsv / ix_chunks_content_tsv because the models never
    # declared them, so from the model diff's point of view they were indexes nobody asked
    # for. Both are declared in core/models.py as of M9
    # (Index(..., postgresql_using="gin")), and autogenerate now round-trips them cleanly.
    # Autogenerate first, then review, is the rule; verified by a throwaway revision.
    #
    # Nullable is load-bearing, not defensive — the M6 embedding
    # stage selects WHERE embedding IS NULL so a 429 partway through a repo resumes
    # instead of restarting, and a repo stuck mid-embed stays searchable via lexical.
    #
    # No HNSW/IVFFlat index here (see docs/DATA_MODEL.md's deferred-and-why entry): our
    # per-file cap forces a full sort over every chunk in the repo already, so an ANN
    # index would sit unused by the only query that reads this column. Exact cosine
    # search over a few thousand chunks is tens of milliseconds — fast enough as-is.
    op.add_column('chunks', sa.Column('embedding', Vector(1536), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('chunks', 'embedding')
