"""add_reference_edge

Revision ID: d7e8f9a0b1c2
Revises: c4d5e6f7a8b9
Create Date: 2026-09-06

The call graph: entity -> entity, as opposed to dependency_edges' file -> file. Written by
hand rather than autogenerated, because autogenerate cannot see the raw-SQL GIN indexes on
files.content_tsv / chunks.content_tsv and proposes dropping them on any table change.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e8f9a0b1c2'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'reference_edges',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('repository_id', sa.UUID(), nullable=False),
        sa.Column('from_entity_id', sa.UUID(), nullable=False),
        sa.Column('to_entity_id', sa.UUID(), nullable=False),
        sa.Column('line', sa.Integer(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['from_entity_id'], ['code_entities.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['to_entity_id'], ['code_entities.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_reference_edges_repository_id'), 'reference_edges', ['repository_id'], unique=False)
    op.create_index(op.f('ix_reference_edges_from_entity_id'), 'reference_edges', ['from_entity_id'], unique=False)
    # get_callers scans by target — the reverse direction is the one that needs its own
    # composite index, since get_callees is already served by from_entity_id above.
    op.create_index(
        'ix_reference_edges_repository_id_to_entity_id',
        'reference_edges',
        ['repository_id', 'to_entity_id'],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_reference_edges_repository_id_to_entity_id', table_name='reference_edges')
    op.drop_index(op.f('ix_reference_edges_from_entity_id'), table_name='reference_edges')
    op.drop_index(op.f('ix_reference_edges_repository_id'), table_name='reference_edges')
    op.drop_table('reference_edges')
