"""add_metric

Revision ID: e9f0a1b2c3d4
Revises: d7e8f9a0b1c2
Create Date: 2026-09-06

The dashboard's aggregates, written once by the metrics pipeline stage. Written by hand
rather than autogenerated. The reason recorded here was WRONG: autogenerate proposed dropping
the two content_tsv GIN indexes not because it could not see them, but because the models
never declared them. They are declared as of M9 and autogenerate round-trips them cleanly.

No enum change is needed for the METRICS/READY statuses this stage finally reaches — the
repository_status type was created with all nine values back in 002ecfb88441.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e9f0a1b2c3d4'
down_revision: Union[str, Sequence[str], None] = 'd7e8f9a0b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'metrics',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('repository_id', sa.UUID(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('repository_id', 'key', name='uq_metrics_repository_id_key'),
    )
    op.create_index(op.f('ix_metrics_repository_id'), 'metrics', ['repository_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_metrics_repository_id'), table_name='metrics')
    op.drop_table('metrics')
