"""add_dependency_edge

Revision ID: fb86cf1b15fb
Revises: 4e35f936f155
Create Date: 2026-07-24 00:53:18.352066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb86cf1b15fb'
down_revision: Union[str, Sequence[str], None] = '4e35f936f155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dependency_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repository_id', sa.UUID(), nullable=False),
    sa.Column('from_file_id', sa.UUID(), nullable=False),
    sa.Column('to_file_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('IMPORT', name='dependency_kind'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_edges_repository_id'), 'dependency_edges', ['repository_id'], unique=False)
    # NOTE: autogenerate also proposed dropping ix_code_entities_name_trgm and
    # ix_files_content_tsv here — both real indexes. The reason given at the time
    # ("invisible to the model diff") was wrong: they were proposed for removal because
    # the models never declared them, which reads as "an index nobody asked for".
    # ix_files_content_tsv is declared as of M9; ix_code_entities_name_trgm was dropped
    # outright in 7a96b345a5d0. Deliberately not touching either in this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dependency_edges_repository_id'), table_name='dependency_edges')
    op.drop_table('dependency_edges')
    # ### end Alembic commands ###
